export interface CameraConfig {
  DEFAULT_DISTANCE: number
  MIN_DISTANCE: number
  MAX_DISTANCE: number
  DEFAULT_HEIGHT_OFFSET: number
  MIN_ELEVATION: number
  MAX_ELEVATION: number
  DEFAULT_FOV: number
  CINEMATIC_FOV: number
  PHOTO_FOV: number
  LOOK_SMOOTHING: number
  ZOOM_SPEED: number
  COLLISION_RADIUS: number
  COLLISION_SMOOTHING: number
  SPRING_STIFFNESS: number
  SPRING_DAMPING: number
  SHOULDER_OFFSET: number
  SPRINT_FOV_BOOST: number
  SPRINT_DISTANCE_BOOST: number
  AUTO_REALIGN_DELAY: number
  AUTO_REALIGN_SPEED: number
  CAMERA_MIN_Y_OFFSET: number
}

export const CAMERA_CONFIG: CameraConfig = {
  DEFAULT_DISTANCE: 7,
  MIN_DISTANCE: 2,
  MAX_DISTANCE: 14,
  DEFAULT_HEIGHT_OFFSET: 2.0,
  MIN_ELEVATION: -Math.PI / 18,
  MAX_ELEVATION: Math.PI / 3,
  DEFAULT_FOV: 65,
  CINEMATIC_FOV: 45,
  PHOTO_FOV: 35,
  LOOK_SMOOTHING: 18,
  ZOOM_SPEED: 0.5,
  COLLISION_RADIUS: 0.5,
  COLLISION_SMOOTHING: 12,
  SPRING_STIFFNESS: 100,
  SPRING_DAMPING: 22,
  SHOULDER_OFFSET: 0.5,
  SPRINT_FOV_BOOST: 5,
  SPRINT_DISTANCE_BOOST: 1.5,
  AUTO_REALIGN_DELAY: 1.5,
  AUTO_REALIGN_SPEED: 2,
  CAMERA_MIN_Y_OFFSET: 0.3,
}
