export interface CameraConfig {
  DEFAULT_DISTANCE: number
  MIN_DISTANCE: number
  MAX_DISTANCE: number
  DEFAULT_HEIGHT_OFFSET: number
  MIN_ELEVATION: number
  MAX_ELEVATION: number
  DEFAULT_FOV: number
  CINEMATIC_FOV: number
  PHOTO_FOV: number
  LOOK_SMOOTHING: number
  POSITION_SMOOTHING: number
  ZOOM_SPEED: number
  ORBIT_SPEED: number
  COLLISION_RADIUS: number
  COLLISION_SMOOTHING: number
  DEFAULT_MODE: string
}

export const CAMERA_CONFIG: CameraConfig = {
  DEFAULT_DISTANCE: 5,
  MIN_DISTANCE: 1.5,
  MAX_DISTANCE: 12,
  DEFAULT_HEIGHT_OFFSET: 0.8,
  MIN_ELEVATION: -Math.PI / 6,
  MAX_ELEVATION: Math.PI / 3,
  DEFAULT_FOV: 60,
  CINEMATIC_FOV: 45,
  PHOTO_FOV: 35,
  LOOK_SMOOTHING: 5,
  POSITION_SMOOTHING: 8,
  ZOOM_SPEED: 0.2,
  ORBIT_SPEED: 2,
  COLLISION_RADIUS: 0.3,
  COLLISION_SMOOTHING: 10,
  DEFAULT_MODE: 'third-person',
}
