export interface CameraConfig {
  DEFAULT_DISTANCE: number
  MIN_DISTANCE: number
  MAX_DISTANCE: number
  DEFAULT_HEIGHT_OFFSET: number
  MIN_ELEVATION: number
  MAX_ELEVATION: number
  DEFAULT_FOV: number
  CINEMATIC_FOV: number
  PHOTO_FOV: number
  LOOK_SMOOTHING: number
  ZOOM_SPEED: number
  COLLISION_RADIUS: number
  COLLISION_SMOOTHING: number
  DEFAULT_MODE: string
  SPRING_STIFFNESS: number
  SPRING_DAMPING: number
  SHOULDER_OFFSET: number
  SPRINT_FOV_BOOST: number
  SPRINT_DISTANCE_BOOST: number
}

export const CAMERA_CONFIG: CameraConfig = {
  DEFAULT_DISTANCE: 7,
  MIN_DISTANCE: 2,
  MAX_DISTANCE: 14,
  DEFAULT_HEIGHT_OFFSET: 1.2,
  MIN_ELEVATION: -Math.PI / 12,
  MAX_ELEVATION: Math.PI / 3,
  DEFAULT_FOV: 65,
  CINEMATIC_FOV: 45,
  PHOTO_FOV: 35,
  LOOK_SMOOTHING: 18,
  ZOOM_SPEED: 0.5,
  COLLISION_RADIUS: 0.5,
  COLLISION_SMOOTHING: 12,
  DEFAULT_MODE: 'third-person',
  SPRING_STIFFNESS: 80,
  SPRING_DAMPING: 18,
  SHOULDER_OFFSET: 0.5,
  SPRINT_FOV_BOOST: 5,
  SPRINT_DISTANCE_BOOST: 1.5,
}
