export const AUDIO_CONFIG = {
  POOL_SIZE: 32,
  MAX_CONCURRENT: 16,
  DEFAULT_FADE_DURATION: 0.5,
  SPATIAL_MODEL: 'HRTF' as const,
  CROSSFADE_DURATION: 1,
  DEFAULT_VOLUME: 0.8,
  DEFAULT_MUSIC_VOLUME: 0.7,
  DEFAULT_SFX_VOLUME: 0.8,
  DEFAULT_VOICE_VOLUME: 0.8,
} as const
